### ISSUE TITLE
Library does not work

### ISSUE THREAD

**Issue by pzehle** [ptr0x01/kanboard-plugin-zulip#7]
On a fresh installation, setting the required data from the bot will not work.

Nothing is happening after moving cards, creating cards, nothing.

Made sure that the filter is empty, also tried by setting filters. In the end, I tried by hard-coding the values from the bot directly in the code, still nothing.

I know is the library because with the exact same details I can just `curl` for testing and it actually works.

Any thoughts?

**Comment by pzehle** [comment]
Nothing? This library continues to not work at all... I don't really understand why taking the time to create something for people to use, but not even give a little bit of time when something doesn't work.

**Comment by ptr0x1** [comment]
Hey Pablo, I no longer use this setup for work so I don't maintain it. You are looking at this backwards - I created something useful that I needed and shared it in case others have the same need. I have no obligations to you or anyone else to maintain it but you are more than welcome to look at it and update it for the new version, maybe help yourself and others after you like I did at some point. :) 

My guess is that something broke with the plugin interaction in a newer version that needs a change in the code, so you can downgrade the version or look at the diff and update it.

**Comment by pzehle** [comment]
Thank you for your response. I don't mean that you have any obligation whatsoever on helping people, I just mean that if people are having problems with the library, it would be nice to receive a response, whatever it may contain, so people can continue working on their own. It took you 10 days to respond to my second comment, as the first one just got ignored.

I appreciate the effort for the library and I will do as you suggest. Thank you.
